"""
Project Euler Solutions

A collection of solutions to Project Euler problems demonstrating
clean code practices and pythonic programming patterns.

Project Euler is a series of challenging mathematical and computer programming
problems that require both mathematical insight and programming skill to solve.
Problems range from simple to very difficult and build upon concepts from
number theory, combinatorics, and computational geometry.

Reference: https://projecteuler.net/
"""

from functools import reduce
from typing import Generator, List, Tuple
import math
import operator
import numpy as np

# ============================================================================
# Problem 1: Multiples of 3 or 5
# ============================================================================
# If we list all the natural numbers below 10 that are multiples of 3 or 5,
# we get 3, 5, 6 and 9. The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.
# Reference: https://projecteuler.net/problem=1

def problem1(n: int) -> int:
    """Calculate the sum of multiples of 3 or 5 below n."""
    return sum(i for i in range(n) if i % 3 == 0 or i % 5 == 0)


# ============================================================================
# Problem 2: Even Fibonacci Numbers
# ============================================================================
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
# Find the sum of the even-valued Fibonacci terms below n.
# Reference: https://projecteuler.net/problem=2

def fibonacci_generator(limit: int) -> Generator[int, None, None]:
    """Generate Fibonacci numbers up to limit."""
    a, b = 0, 1
    while b < limit:
        yield b
        a, b = b, a + b


def problem2(n: int) -> int:
    """Calculate the sum of even Fibonacci numbers below n."""
    return sum(fib for fib in fibonacci_generator(n) if fib % 2 == 0)


# ============================================================================
# Problem 3: Largest Prime Factor
# ============================================================================
# The prime factors of 13195 are 5, 7, 13 and 29.
# What is the largest prime factor of the number 600851475143?
# Reference: https://projecteuler.net/problem=3

def largest_prime_factor(n: int) -> int:
    """Find the largest prime factor of n."""
    max_prime = 2
    divisor = 2
    while n % 2 == 0:
        n //= 2
    if n == 1:
        return 2

    while divisor * divisor <= n:
        if n % divisor == 0:
            n //= divisor
        else:
            divisor += 2

    return n


def problem3(n: int) -> int:
    """Return the largest prime factor of n."""
    return largest_prime_factor(n)


# ============================================================================
# Problem 4: Largest Palindrome Product
# ============================================================================
# A palindromic number reads the same both ways.
# The largest palindrome made from the product of two 2-digit numbers is 9009.
# Find the largest palindrome made from the product of two n-digit numbers.
# Reference: https://projecteuler.net/problem=4

def is_palindrome(n: int) -> bool:
    """Check if a number is a palindrome."""
    s = str(n)
    return s == s[::-1]


def problem4(num_digits: int) -> int:
    """Find the largest palindrome from product of n-digit numbers."""
    min_num = 10 ** (num_digits - 1)
    max_num = 10 ** num_digits

    return max(
        (i * j for i in range(min_num, max_num)
         for j in range(i, max_num) if is_palindrome(i * j)),
        default=0
    )


# ============================================================================
# Problem 5: Smallest Multiple
# ============================================================================
# 2520 is the smallest number that can be divided by each of the numbers
# from 1 to 10 without any remainder.
# What is the smallest positive number evenly divisible by 1 to n?
# Reference: https://projecteuler.net/problem=5

def problem5(n: int) -> int:
    """Find the smallest positive number evenly divisible by 1 to n."""
    return reduce(math.lcm, range(1, n + 1))

# ============================================================================
# Problem 6: Sum Square Difference
# ============================================================================
# The sum of the squares of the first ten natural numbers is 385.
# The square of the sum is 3025.
# Find the difference between the sum of squares and square of sum.
# Reference: https://projecteuler.net/problem=6

def problem6(n: int) -> int:
    """Calculate difference between sum of squares and square of sum."""
    numbers = range(1, n + 1)
    sum_of_squares = sum(i ** 2 for i in numbers)
    square_of_sum = sum(numbers) ** 2
    return square_of_sum - sum_of_squares


# ============================================================================
# Problem 7: 10001st Prime
# ============================================================================
# By listing the first six primes: 2, 3, 5, 7, 11, and 13,
# we can see that the 6th prime is 13.
# What is the 10001st prime number?
# Reference: https://projecteuler.net/problem=7

def nth_prime(n: int) -> int:
    """Find the nth prime number."""
    limit = int(n*(math.log(n) + math.log(math.log(n))))
    sieve = [True] * (limit + 1)
    count = 0

    for p in range(2, limit + 1):
        if sieve[p]:
            count += 1
            if count == n:
                return p
            # Mark multiples of p as not prime
            for i in range(p * p, limit + 1, p):
                sieve[i] = False


def problem7(n: int) -> int:
    """Return the nth prime number."""
    return nth_prime(n)


# ============================================================================
# Problem 8: Largest Product in a Series
# ============================================================================
# Find the thirteen adjacent digits in a 1000-digit number with greatest
# product. What is the value of this product?
# Reference: https://projecteuler.net/problem=8

LARGE_NUMBER = (
    "73167176531330624919225119674426574742355349194934"
    "96983520312774506326239578318016984801869478851843"
    "85861560789112949495459501737958331952853208805511"
    "12540698747158523863050715693290963295227443043557"
    "66896648950445244523161731856403098711121722383113"
    "62229893423380308135336276614282806444486645238749"
    "30358907296290491560440772390713810515859307960866"
    "70172427121883998797908792274921901699720888093776"
    "65727333001053367881220235421809751254540594752243"
    "52584907711670556013604839586446706324415722155397"
    "53697817977846174064955149290862569321978468622482"
    "83972241375657056057490261407972968652414535100474"
    "82166370484403199890008895243450658541227588666881"
    "16427171479924442928230863465674813919123162824586"
    "17866458359124566529476545682848912883142607690042"
    "24219022671055626321111109370544217506941658960408"
    "07198403850962455444362981230987879927244284909188"
    "84580156166097919133875499200524063689912560717606"
    "05886116467109405077541002256983155200055935729725"
    "71636269561882670428252483600823257530420752963450"
)


def largest_product_in_series(digits_str: str, series_length: int) -> int:
    """Find the largest product of series_length consecutive digits."""
    digit_list = [int(d) for d in digits_str]
    max_product = 0

    for i in range(len(digit_list) - series_length + 1):
        product = reduce(operator.mul, digit_list[i:i + series_length], 1)
        max_product = max(max_product, product)

    return max_product


def problem8(n: int) -> int:
    """Find the largest product of n adjacent digits in LARGE_NUMBER."""
    return largest_product_in_series(LARGE_NUMBER, n)


# ============================================================================
# Problem 9: Special Pythagorean Triplet
# ============================================================================
# A Pythagorean triplet is a set of three natural numbers a < b < c
# where a^2 + b^2 = c^2. Find the product abc where a + b + c = n.
# Reference: https://projecteuler.net/problem=9

def find_pythagorean_triplet(n: int) -> Tuple[int, int, int]:
    """Find Pythagorean triplet where a + b + c = n."""
    for m in range(2, int(math.sqrt(n)) + 1):
        for k in range(1, m):
            a = m * m - k * k
            b = 2 * m * k
            c = m * m + k * k
            if a + b + c == n:
                return tuple(sorted([a, b, c]))
    return (0, 0, 0)


def problem9(n: int) -> int:
    """Return the product abc of Pythagorean triplet summing to n."""
    a, b, c = find_pythagorean_triplet(n)
    return a * b * c


# ============================================================================
# Problem 10: Summation of Primes
# ============================================================================
# Find the sum of all primes below n.
# Reference: https://projecteuler.net/problem=10
# Uses Sieve of Eratosthenes: https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes

def sieve_of_eratosthenes(limit: int) -> List[int]:
    """Return all prime numbers below limit using Sieve of Eratosthenes."""
    is_prime = [True] * (limit + 1)
    is_prime[0] = is_prime[1] = False

    for p in range(2, int(math.sqrt(limit)) + 1):
        if is_prime[p]:
            for i in range(p * p, limit + 1, p):
                is_prime[i] = False

    return [num for num, prime in enumerate(is_prime) if prime]


def problem10(n: int) -> int:
    """Return the sum of all primes below n."""
    return sum(sieve_of_eratosthenes(n))


def problem11(n: int) -> int:

    input = """
08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48"""

    grid = [[int(x) for x in row.split()] for row in input.strip().split("\n")]
    max_size = len(grid[0])
    if max_size < n:
        return 0

    max_total = 0
    for row in range(max_size):
        for col in range(max_size - n + 1):
            window = grid[row][col:col + n]
            prod = math.prod(window)
            max_total = max(max_total, prod)

    for col in range(max_size):
        for row in range(max_size - n + 1):
            window = [grid[row + i][col] for i in range(n)]
            prod = math.prod(window)
            max_total = max(max_total, prod)

    for row in range(max_size - n + 1):
        for col in range(max_size - n + 1):
            window = [grid[row + i][col + i] for i in range(n)]
            prod = math.prod(window)
            max_total = max(max_total, prod)

    for row in range(max_size - n + 1):
        for col in range(max_size - n + 1):
            window = [grid[n + row - i - 1][col + i] for i in range(n)]
            prod = math.prod(window)
            max_total = max(max_total, prod)

    return max_total


# ============================================================================
# Problem 12: Highly Divisible Triangular Number
# ============================================================================
# What is the value of the first triangle number to have over n divisors?
# Reference: https://projecteuler.net/problem=12

def count_divisors(n: int) -> int:
    """Count the number of divisors of n."""
    divisor_count = 0
    sqrt_n = int(math.sqrt(n)) + 1
    for i in range(1, sqrt_n):
        if n % i == 0:
            divisor_count += 2
    if int(math.sqrt(n)) ** 2 == n:
        divisor_count -= 1
    return divisor_count


def problem12(min_divisors: int) -> int:
    """Find first triangle number with over min_divisors divisors."""
    triangular_num = 0
    i = 0

    while count_divisors(triangular_num) < min_divisors:
        i += 1
        triangular_num += i

    return triangular_num


# ============================================================================
# Problem 13: Large Sum
# ============================================================================
# Work out the first n digits of the sum of 100 50-digit numbers.
# Reference: https://projecteuler.net/problem=13

LARGE_NUMBERS = [
    37107287533902102798797998220837590246510135740250,
    46376937677490009712648124896970078050417018260538,
    74324986199524741059474233309513058123726617309629,
    91942213363574161572522430563301811072406154908250,
    23067588207539346171171980310421047513778063246676,
    89261670696623633820136378418383684178734361726757,
    28112879812849979408065481931592621691275889832738,
    44274228917432520321923589422876796487670272189318,
    47451445736001306439091167216856844588711603153276,
    70386486105843025439939619828917593665686757934951,
    62176457141856560629502157223196586755079324193331,
    64906352462741904929101432445813822663347944758178,
    92575867718337217661963751590579239728245598838407,
    58203565325359399008402633568948830189458628227828,
    80181199384826282014278194139940567587151170094390,
    35398664372827112653829987240784473053190104293586,
    86515506006295864861532075273371959191420517255829,
    71693888707715466499115593487603532921714970056938,
    54370070576826684624621495650076471787294438377604,
    53282654108756828443191190634694037855217779295145,
    36123272525000296071075082563815656710885258350721,
    45876576172410976447339110607218265236877223636045,
    17423706905851860660448207621209813287860733969412,
    81142660418086830619328460811191061556940512689692,
    51934325451728388641918047049293215058642563049483,
    62467221648435076201727918039944693004732956340691,
    15732444386908125794514089057706229429197107928209,
    55037687525678773091862540744969844508330393682126,
    18336384825330154686196124348767681297534375946515,
    80386287592878490201521685554828717201219257766954,
    78182833757993103614740356856449095527097864797581,
    16726320100436897842553539920931837441497806860984,
    48403098129077791799088218795327364475675590848030,
    87086987551392711854517078544161852424320693150332,
    59959406895756536782107074926966537676326235447210,
    69793950679652694742597709739166693763042633987085,
    41052684708299085211399427365734116182760315001271,
    65378607361501080857009149939512557028198746004375,
    35829035317434717326932123578154982629742552737307,
    94953759765105305946966067683156574377167401875275,
    88902802571733229619176668713819931811048770190271,
    25267680276078003013678680992525463401061632866526,
    36270218540497705585629946580636237993140746255962,
    24074486908231174977792365466257246923322810917141,
    91430288197103288597806669760892938638285025333403,
    34413065578016127815921815005561868836468420090470,
    23053081172816430487623791969842487255036638784583,
    11487696932154902810424020138335124462181441773470,
    63783299490636259666498587618221225225512486764533,
    67720186971698544312419572409913959008952310058822,
    95548255300263520781532296796249481641953868218774,
    76085327132285723110424803456124867697064507995236,
    37774242535411291684276865538926205024910326572967,
    23701913275725675285653248258265463092207058596522,
    29798860272258331913126375147341994889534765745501,
    18495701454879288984856827726077713721403798879715,
    38298203783031473527721580348144513491373226651381,
    34829543829199918180278916522431027392251122869539,
    40957953066405232632538044100059654939159879593635,
    29746152185502371307642255121183693803580388584903,
    41698116222072977186158236678424689157993532961922,
    62467957194401269043877107275048102390895523597457,
    23189706772547915061505504953922979530901129967519,
    86188088225875314529584099251203829009407770775672,
    11306739708304724483816533873502340845647058077308,
    82959174767140363198008187129011875491310547126581,
    97623331044818386269515456334926366572897563400500,
    42846280183517070527831839425882145521227251250327,
    55121603546981200581762165212827652751691296897789,
    32238195734329339946437501907836945765883352399886,
    75506164965184775180738168837861091527357929701337,
    62177842752192623401942399639168044983993173312731,
    32924185707147349566916674687634660915035914677504,
    99518671430235219628894890102423325116913619626622,
    73267460800591547471830798392868535206946944540724,
    76841822524674417161514036427982273348055556214818,
    97142617910342598647204516893989422179826088076852,
    87783646182799346313767754307809363333018982642090,
    10848802521674670883215120185883543223812876952786,
    71329612474782464538636993009049310363619763878039,
    62184073572399794223406235393808339651327408011116,
    66627891981488087797941876876144230030984490851411,
    60661826293682836764744779239180335110989069790714,
    85786944089552990653640447425576083659976645795096,
    66024396409905389607120198219976047599490197230297,
    64913982680032973156037120041377903785566085089252,
    16730939319872750275468906903707539413042652315011,
    94809377245048795150954100921645863754710598436791,
    78639167021187492431995700641917969777599028300699,
    15368713711936614952811305876380278410754449733078,
    40789923115535562561142322423255033685442488917353,
    44889911501440648020369068063960672322193204149535,
    41503128880339536053299340368006977710650566631954,
    81234880673210146739058568557934581403627822703280,
    82616570773948327592232845941706525094512325230608,
    22918802058777319719839450180888072429661980811197,
    77158542502016545090413245809786882778948721859617,
    72107838435069186155435662884062257473692284509516,
    20849603980134001723930671666823555245252804609722,
    53503534226472524250874054075591789781264330331690,
]


def problem13(num_digits: int) -> int:
    """Return first n digits of the sum of LARGE_NUMBERS."""
    total = sum(LARGE_NUMBERS)
    return int(str(total)[:num_digits])


# ============================================================================
# Problem 14: Longest Collatz Sequence
# ============================================================================
# Which starting number, under one million, produces the longest chain?
# Reference: https://projecteuler.net/problem=14

def collatz_chain_length(n: int) -> int:
    """Calculate the length of the Collatz sequence starting at n."""
    length = 1
    while n != 1:
        length += 1
        n = n // 2 if n % 2 == 0 else 3 * n + 1
    return length


def problem14(limit: int) -> int:
    """Find the starting number under limit with longest Collatz chain."""
    return max(
        range(1, limit),
        key=collatz_chain_length
    )


# ============================================================================
# Problem 16: Power Digit Sum
# ============================================================================
# 2^15 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.
# What is the sum of the digits of the number 2^n?
# Reference: https://projecteuler.net/problem=16

def digit_sum(n: int) -> int:
    """Calculate the sum of digits of n."""
    return sum(int(digit) for digit in str(n))


def problem16(n: int) -> int:
    """Return the sum of digits of 2^n."""
    return digit_sum(2 ** n)


# ============================================================================
# Problem 17: Number Letter Counts
# ============================================================================
# If the numbers 1 to 5 are written out in words: one, two, three, four, five,
# then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.
# Find the total number of letters used if all numbers 1 to n are written out.
# Reference: https://projecteuler.net/problem=17

def number_to_words_length(n: int) -> int:
    """Return the number of letters in English word representation of n."""
    ones = ["", "one", "two", "three", "four", "five", "six", "seven",
            "eight", "nine", "ten", "eleven", "twelve", "thirteen",
            "fourteen", "fifteen", "sixteen", "seventeen", "eighteen",
            "nineteen"]
    tens = ["", "", "twenty", "thirty", "forty", "fifty", "sixty",
            "seventy", "eighty", "ninety"]

    if n == 0:
        return 0
    elif n < 20:
        return len(ones[n])
    elif n < 100:
        return len(tens[n // 10]) + len(ones[n % 10])
    elif n < 1000:
        result = len(ones[n // 100]) + len("hundred")
        if n % 100 != 0:
            result += len("and") + number_to_words_length(n % 100)
        return result
    elif n == 1000:
        return len("onethousand")


def problem17(n: int) -> int:
    """Return total number of letters used writing numbers 1 to n in words."""
    return sum(number_to_words_length(i) for i in range(1, n + 1))


# ============================================================================
# Problem 20: Factorial Digit Sum
# ============================================================================
# n! means n × (n-1) × ... × 3 × 2 × 1. For example, 10! = 3628800,
# and the sum of the digits is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.
# Find the sum of the digits in the number n!
# Reference: https://projecteuler.net/problem=20

def problem20(n: int) -> int:
    """Return the sum of digits of n!"""
    return digit_sum(math.factorial(n))


# ============================================================================
# Main Execution
# ============================================================================

if __name__ == "__main__":
    print("=" * 70)
    print("PROJECT EULER SOLUTIONS")
    print("=" * 70 + "\n")

    print(f"Problem 1  - Sum of multiples of 3 or 5 below 1000:                {problem1(1000)}")
    print(f"Problem 2  - Sum of even Fibonacci numbers below 4,000,000:        {problem2(4000000)}")
    print(f"Problem 3  - Largest prime factor of 600,851,475,143:              {problem3(600851475143)}")
    print(f"Problem 4  - Largest palindrome product of 3-digit numbers:        {problem4(3)}")
    print(f"Problem 5  - Smallest multiple of 1-20:                            {problem5(20)}")
    print(f"Problem 6  - Sum square difference for first 100 numbers:          {problem6(100)}")
    print(f"Problem 7  - The 10001st prime number:                             {problem7(10001)}")
    print(f"Problem 8  - Largest product of 13 adjacent digits:                {problem8(13)}")
    print(f"Problem 9  - Pythagorean triplet product (a+b+c=1000):             {problem9(1000)}")
    print(f"Problem 10 - Sum of primes below 2,000,000:                        {problem10(2000000)}")
    print(f"Problem 11 - Greatest product of 4 adjacent numbers               {problem11(4)}")
    print(f"Problem 12 - First triangle number with 500+ divisors:             {problem12(500)}")
    print(f"Problem 13 - First 10 digits of large sum:                         {problem13(10)}")
    print(f"Problem 14 - Starting number under 1,000,000 with longest Collatz: {problem14(1000000)}")
    print(f"Problem 16 - Sum of digits of 2^1000:                              {problem16(1000)}")
    print(f"Problem 17 - Number letter counts for 1-1000:                      {problem17(1000)}")
    print(f"Problem 20 - Sum of digits of 100!:                                {problem20(100)}")
