"""
Project Euler Solutions

A collection of solutions to Project Euler problems demonstrating
clean code practices and pythonic programming patterns.

Reference: https://projecteuler.net/
"""

from functools import reduce
from typing import Generator, List, Tuple
import itertools
import math
import operator


class ProjectEuler:
    """Base class for Project Euler problem solutions."""

    @staticmethod
    def _print_result(problem_num: int, description: str, result: int) -> None:
        """Print solution result in a consistent format."""
        print(f"Problem {problem_num}: {description}")
        print(f"Answer: {result}\n")


# ============================================================================
# Problem 1: Multiples of 3 or 5
# ============================================================================
# If we list all the natural numbers below 10 that are multiples of 3 or 5,
# we get 3, 5, 6 and 9. The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.
# Reference: https://projecteuler.net/problem=1

def problem1(n: int) -> int:
    """Calculate the sum of multiples of 3 or 5 below n."""
    return sum(i for i in range(n) if i % 3 == 0 or i % 5 == 0)


# ============================================================================
# Problem 2: Even Fibonacci Numbers
# ============================================================================
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
# Find the sum of the even-valued Fibonacci terms below n.
# Reference: https://projecteuler.net/problem=2

def fibonacci_generator(limit: int) -> Generator[int, None, None]:
    """Generate Fibonacci numbers up to limit."""
    a, b = 0, 1
    while b < limit:
        yield b
        a, b = b, a + b


def problem2(n: int) -> int:
    """Calculate the sum of even Fibonacci numbers below n."""
    return sum(fib for fib in fibonacci_generator(n) if fib % 2 == 0)


# ============================================================================
# Problem 3: Largest Prime Factor
# ============================================================================
# The prime factors of 13195 are 5, 7, 13 and 29.
# What is the largest prime factor of the number 600851475143?
# Reference: https://projecteuler.net/problem=3

def largest_prime_factor(n: int) -> int:
    """Find the largest prime factor of n."""
    dividend = n
    sqrt_n = int(math.sqrt(n))
    max_prime = 2
    divisor = 2

    while divisor <= sqrt_n and dividend > 1:
        if dividend % divisor == 0:
            dividend //= divisor
            max_prime = divisor
        else:
            divisor += 1

    return max(max_prime, dividend) if dividend > 1 else max_prime


def problem3(n: int) -> int:
    """Return the largest prime factor of n."""
    return largest_prime_factor(n)


# ============================================================================
# Problem 4: Largest Palindrome Product
# ============================================================================
# A palindromic number reads the same both ways.
# The largest palindrome made from the product of two 2-digit numbers is 9009.
# Find the largest palindrome made from the product of two n-digit numbers.
# Reference: https://projecteuler.net/problem=4

def is_palindrome(n: int) -> bool:
    """Check if a number is a palindrome."""
    s = str(n)
    return s == s[::-1]


def problem4(num_digits: int) -> int:
    """Find the largest palindrome from product of n-digit numbers."""
    min_num = 10 ** (num_digits - 1)
    max_num = 10 ** num_digits

    return max(
        (i * j for i in range(min_num, max_num)
         for j in range(min_num, max_num) if is_palindrome(i * j)),
        default=0
    )


# ============================================================================
# Problem 5: Smallest Multiple
# ============================================================================
# 2520 is the smallest number that can be divided by each of the numbers
# from 1 to 10 without any remainder.
# What is the smallest positive number evenly divisible by 1 to n?
# Reference: https://projecteuler.net/problem=5

def problem5(n: int) -> int:
    """Find the smallest positive number evenly divisible by 1 to n."""
    current = n
    while True:
        if all(current % i == 0 for i in range(1, n + 1)):
            return current
        current += n


# ============================================================================
# Problem 6: Sum Square Difference
# ============================================================================
# The sum of the squares of the first ten natural numbers is 385.
# The square of the sum is 3025.
# Find the difference between the sum of squares and square of sum.
# Reference: https://projecteuler.net/problem=6

def problem6(n: int) -> int:
    """Calculate difference between sum of squares and square of sum."""
    numbers = range(1, n + 1)
    sum_of_squares = sum(i ** 2 for i in numbers)
    square_of_sum = sum(numbers) ** 2
    return square_of_sum - sum_of_squares


# ============================================================================
# Problem 7: 10001st Prime
# ============================================================================
# By listing the first six primes: 2, 3, 5, 7, 11, and 13,
# we can see that the 6th prime is 13.
# What is the 10001st prime number?
# Reference: https://projecteuler.net/problem=7

def nth_prime(n: int) -> int:
    """Find the nth prime number."""
    primes: List[int] = []
    candidate = 2

    while len(primes) < n:
        if all(candidate % p != 0 for p in primes):
            primes.append(candidate)
        candidate += 1

    return primes[-1]


def problem7(n: int) -> int:
    """Return the nth prime number."""
    return nth_prime(n)


# ============================================================================
# Problem 8: Largest Product in a Series
# ============================================================================
# Find the thirteen adjacent digits in a 1000-digit number with greatest
# product. What is the value of this product?
# Reference: https://projecteuler.net/problem=8

LARGE_NUMBER = (
    "73167176531330624919225119674426574742355349194934"
    "96983520312774506326239578318016984801869478851843"
    "85861560789112949495459501737958331952853208805511"
    "12540698747158523863050715693290963295227443043557"
    "66896648950445244523161731856403098711121722383113"
    "62229893423380308135336276614282806444486645238749"
    "30358907296290491560440772390713810515859307960866"
    "70172427121883998797908792274921901699720888093776"
    "65727333001053367881220235421809751254540594752243"
    "52584907711670556013604839586446706324415722155397"
    "53697817977846174064955149290862569321978468622482"
    "83972241375657056057490261407972968652414535100474"
    "82166370484403199890008895243450658541227588666881"
    "16427171479924442928230863465674813919123162824586"
    "17866458359124566529476545682848912883142607690042"
    "24219022671055626321111109370544217506941658960408"
    "07198403850962455444362981230987879927244284909188"
    "84580156166097919133875499200524063689912560717606"
    "05886116467109405077541002256983155200055935729725"
    "71636269561882670428252483600823257530420752963450"
)


def largest_product_in_series(digits_str: str, series_length: int) -> int:
    """Find the largest product of series_length consecutive digits."""
    digit_list = [int(d) for d in digits_str]
    max_product = 0

    for i in range(len(digit_list) - series_length + 1):
        product = reduce(operator.mul, digit_list[i:i + series_length], 1)
        max_product = max(max_product, product)

    return max_product


def problem8(n: int) -> int:
    """Find the largest product of n adjacent digits in LARGE_NUMBER."""
    return largest_product_in_series(LARGE_NUMBER, n)


# ============================================================================
# Problem 9: Special Pythagorean Triplet
# ============================================================================
# A Pythagorean triplet is a set of three natural numbers a < b < c
# where a^2 + b^2 = c^2. Find the product abc where a + b + c = n.
# Reference: https://projecteuler.net/problem=9

def find_pythagorean_triplet(n: int) -> Tuple[int, int, int]:
    """Find Pythagorean triplet where a + b + c = n."""
    for m in range(2, int(math.sqrt(n)) + 1):
        for k in range(1, m):
            a = m * m - k * k
            b = 2 * m * k
            c = m * m + k * k
            if a + b + c == n:
                return tuple(sorted([a, b, c]))
    return (0, 0, 0)


def problem9(n: int) -> int:
    """Return the product abc of Pythagorean triplet summing to n."""
    a, b, c = find_pythagorean_triplet(n)
    return a * b * c


# ============================================================================
# Problem 10: Summation of Primes
# ============================================================================
# Find the sum of all primes below n.
# Reference: https://projecteuler.net/problem=10
# Uses Sieve of Eratosthenes: https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes

def sieve_of_eratosthenes(limit: int) -> List[int]:
    """Return all prime numbers below limit using Sieve of Eratosthenes."""
    is_prime = [True] * (limit + 1)
    is_prime[0] = is_prime[1] = False

    for p in range(2, int(math.sqrt(limit)) + 1):
        if is_prime[p]:
            for i in range(p * p, limit + 1, p):
                is_prime[i] = False

    return [num for num, prime in enumerate(is_prime) if prime]


def problem10(n: int) -> int:
    """Return the sum of all primes below n."""
    return sum(sieve_of_eratosthenes(n))


# ============================================================================
# Problem 12: Highly Divisible Triangular Number
# ============================================================================
# What is the value of the first triangle number to have over n divisors?
# Reference: https://projecteuler.net/problem=12

def count_divisors(n: int) -> int:
    """Count the number of divisors of n."""
    divisor_count = 0
    sqrt_n = int(math.sqrt(n)) + 1
    for i in range(1, sqrt_n):
        if n % i == 0:
            divisor_count += 2
    if int(math.sqrt(n)) ** 2 == n:
        divisor_count -= 1
    return divisor_count


def problem12(min_divisors: int) -> int:
    """Find first triangle number with over min_divisors divisors."""
    triangular_num = 0
    i = 0

    while count_divisors(triangular_num) < min_divisors:
        i += 1
        triangular_num += i

    return triangular_num


# ============================================================================
# Problem 13: Large Sum
# ============================================================================
# Work out the first n digits of the sum of 100 50-digit numbers.
# Reference: https://projecteuler.net/problem=13

LARGE_NUMBERS = [
    37107287533902102798797998220837590246510135740250,
    46376937677490009712648124896970078050417018260538,
    74324986199524741059474233309513058123726617309629,
    91942213363574161572522430563301811072406154908250,
    23067588207539346171171980310421047513778063246676,
    89261670696623633820136378418383684178734361726757,
    28112879812849979408065481931592621691275889832738,
    44274228917432520321923589422876796487670272189318,
    47451445736001306439091167216856844588711603153276,
    70386486105843025439939619828917593665686757934951,
    62176457141856560629502157223196586755079324193331,
    64906352462741904929101432445813822663347944758178,
    92575867718337217661963751590579239728245598838407,
    58203565325359399008402633568948830189458628227828,
    80181199384826282014278194139940567587151170094390,
    35398664372827112653829987240784473053190104293586,
    86515506006295864861532075273371959191420517255829,
    71693888707715466499115593487603532921714970056938,
    54370070576826684624621495650076471787294438377604,
    53282654108756828443191190634694037855217779295145,
    36123272525000296071075082563815656710885258350721,
    45876576172410976447339110607218265236877223636045,
    17423706905851860660448207621209813287860733969412,
    81142660418086830619328460811191061556940512689692,
    51934325451728388641918047049293215058642563049483,
    62467221648435076201727918039944693004732956340691,
    15732444386908125794514089057706229429197107928209,
    55037687525678773091862540744969844508330393682126,
    18336384825330154686196124348767681297534375946515,
    80386287592878490201521685554828717201219257766954,
    78182833757993103614740356856449095527097864797581,
    16726320100436897842553539920931837441497806860984,
    48403098129077791799088218795327364475675590848030,
    87086987551392711854517078544161852424320693150332,
    59959406895756536782107074926966537676326235447210,
    69793950679652694742597709739166693763042633987085,
    41052684708299085211399427365734116182760315001271,
    65378607361501080857009149939512557028198746004375,
    35829035317434717326932123578154982629742552737307,
    94953759765105305946966067683156574377167401875275,
    88902802571733229619176668713819931811048770190271,
    25267680276078003013678680992525463401061632866526,
    36270218540497705585629946580636237993140746255962,
    24074486908231174977792365466257246923322810917141,
    91430288197103288597806669760892938638285025333403,
    34413065578016127815921815005561868836468420090470,
    23053081172816430487623791969842487255036638784583,
    11487696932154902810424020138335124462181441773470,
    63783299490636259666498587618221225225512486764533,
    67720186971698544312419572409913959008952310058822,
    95548255300263520781532296796249481641953868218774,
    76085327132285723110424803456124867697064507995236,
    37774242535411291684276865538926205024910326572967,
    23701913275725675285653248258265463092207058596522,
    29798860272258331913126375147341994889534765745501,
    18495701454879288984856827726077713721403798879715,
    38298203783031473527721580348144513491373226651381,
    34829543829199918180278916522431027392251122869539,
    40957953066405232632538044100059654939159879593635,
    29746152185502371307642255121183693803580388584903,
    41698116222072977186158236678424689157993532961922,
    62467957194401269043877107275048102390895523597457,
    23189706772547915061505504953922979530901129967519,
    86188088225875314529584099251203829009407770775672,
    11306739708304724483816533873502340845647058077308,
    82959174767140363198008187129011875491310547126581,
    97623331044818386269515456334926366572897563400500,
    42846280183517070527831839425882145521227251250327,
    55121603546981200581762165212827652751691296897789,
    32238195734329339946437501907836945765883352399886,
    75506164965184775180738168837861091527357929701337,
    62177842752192623401942399639168044983993173312731,
    32924185707147349566916674687634660915035914677504,
    99518671430235219628894890102423325116913619626622,
    73267460800591547471830798392868535206946944540724,
    76841822524674417161514036427982273348055556214818,
    97142617910342598647204516893989422179826088076852,
    87783646182799346313767754307809363333018982642090,
    10848802521674670883215120185883543223812876952786,
    71329612474782464538636993009049310363619763878039,
    62184073572399794223406235393808339651327408011116,
    66627891981488087797941876876144230030984490851411,
    60661826293682836764744779239180335110989069790714,
    85786944089552990653640447425576083659976645795096,
    66024396409905389607120198219976047599490197230297,
    64913982680032973156037120041377903785566085089252,
    16730939319872750275468906903707539413042652315011,
    94809377245048795150954100921645863754710598436791,
    78639167021187492431995700641917969777599028300699,
    15368713711936614952811305876380278410754449733078,
    40789923115535562561142322423255033685442488917353,
    44889911501440648020369068063960672322193204149535,
    41503128880339536053299340368006977710650566631954,
    81234880673210146739058568557934581403627822703280,
    82616570773948327592232845941706525094512325230608,
    22918802058777319719839450180888072429661980811197,
    77158542502016545090413245809786882778948721859617,
    72107838435069186155435662884062257473692284509516,
    20849603980134001723930671666823555245252804609722,
    53503534226472524250874054075591789781264330331690,
]


def problem13(num_digits: int) -> int:
    """Return first n digits of the sum of LARGE_NUMBERS."""
    total = sum(LARGE_NUMBERS)
    return int(str(total)[:num_digits])


# ============================================================================
# Problem 14: Longest Collatz Sequence
# ============================================================================
# Which starting number, under one million, produces the longest chain?
# Reference: https://projecteuler.net/problem=14

def collatz_chain_length(n: int) -> int:
    """Calculate the length of the Collatz sequence starting at n."""
    length = 1
    while n != 1:
        length += 1
        n = n // 2 if n % 2 == 0 else 3 * n + 1
    return length


def problem14(limit: int) -> int:
    """Find the starting number under limit with longest Collatz chain."""
    return max(
        range(1, limit),
        key=collatz_chain_length
    )


# ============================================================================
# Problem 16: Power Digit Sum
# ============================================================================
# 2^15 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.
# What is the sum of the digits of the number 2^n?
# Reference: https://projecteuler.net/problem=16

def digit_sum(n: int) -> int:
    """Calculate the sum of digits of n."""
    return sum(int(digit) for digit in str(n))


def problem16(n: int) -> int:
    """Return the sum of digits of 2^n."""
    return digit_sum(2 ** n)


# ============================================================================
# Problem 20: Factorial Digit Sum
# ============================================================================
# n! means n × (n-1) × ... × 3 × 2 × 1. For example, 10! = 3628800,
# and the sum of the digits is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.
# Find the sum of the digits in the number n!
# Reference: https://projecteuler.net/problem=20

def problem20(n: int) -> int:
    """Return the sum of digits of n!"""
    return digit_sum(math.factorial(n))


# ============================================================================
# Main Execution
# ============================================================================

if __name__ == "__main__":
    # Test cases with smaller values
    print("=" * 70)
    print("PROJECT EULER SOLUTIONS")
    print("=" * 70 + "\n")

    # Problem 1
    result = problem1(1000)
    print(f"Problem 1 - Sum of multiples of 3 or 5 below 1000: {result}\n")

    # Problem 2
    result = problem2(4000000)
    print(f"Problem 2 - Sum of even Fibonacci numbers below 4,000,000: {result}\n")

    # Problem 3
    result = problem3(600851475143)
    print(f"Problem 3 - Largest prime factor of 600,851,475,143: {result}\n")

    # Problem 4
    result = problem4(3)
    print(f"Problem 4 - Largest palindrome product of 3-digit numbers: {result}\n")

    # Problem 5
    result = problem5(20)
    print(f"Problem 5 - Smallest multiple of 1-20: {result}\n")

    # Problem 6
    result = problem6(100)
    print(f"Problem 6 - Sum square difference for first 100 numbers: {result}\n")

    # Problem 7
    result = problem7(10001)
    print(f"Problem 7 - The 10,001st prime number: {result}\n")

    # Problem 8
    result = problem8(13)
    print(f"Problem 8 - Largest product of 13 adjacent digits: {result}\n")

    # Problem 9
    result = problem9(1000)
    print(f"Problem 9 - Pythagorean triplet product (a+b+c=1000): {result}\n")

    # Problem 10
    result = problem10(2000000)
    print(f"Problem 10 - Sum of primes below 2,000,000: {result}\n")

    # Problem 12
    result = problem12(500)
    print(f"Problem 12 - First triangle number with 500+ divisors: {result}\n")

    # Problem 13
    result = problem13(10)
    print(f"Problem 13 - First 10 digits of large sum: {result}\n")

    # Problem 14
    result = problem14(1000000)
    print(f"Problem 14 - Starting number with longest Collatz (< 1M): {result}\n")

    # Problem 16
    result = problem16(1000)
    print(f"Problem 16 - Sum of digits of 2^1000: {result}\n")

    # Problem 20
    result = problem20(100)
    print(f"Problem 20 - Sum of digits of 100!: {result}\n")
